# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `clamby` gem.
# Please instead update this file by running `bin/tapioca gem clamby`.


# source://clamby//lib/clamby/command.rb#1
module Clamby
  class << self
    # Returns the value of attribute config.
    #
    # source://clamby//lib/clamby.rb#30
    def config; end

    # source://clamby//lib/clamby.rb#34
    def configure(opts = T.unsafe(nil)); end

    # @return [Boolean]
    #
    # source://clamby//lib/clamby.rb#68
    def daemonize?; end

    # @return [Boolean]
    #
    # source://clamby//lib/clamby.rb#43
    def safe?(path); end

    # @raise [Clamby::ClamscanMissing]
    # @return [Boolean]
    #
    # source://clamby//lib/clamby.rb#54
    def scanner_exists?; end

    # source://clamby//lib/clamby.rb#64
    def update; end

    # Returns the value of attribute valid_config_keys.
    #
    # source://clamby//lib/clamby.rb#31
    def valid_config_keys; end

    # @return [Boolean]
    #
    # source://clamby//lib/clamby.rb#49
    def virus?(path); end
  end
end

# source://clamby//lib/clamby/error.rb#6
class Clamby::ClamscanClientError < ::Clamby::Error; end

# source://clamby//lib/clamby/error.rb#5
class Clamby::ClamscanMissing < ::Clamby::Error; end

# Interface with the system. Builds and runs the command.
#
# source://clamby//lib/clamby/command.rb#3
class Clamby::Command
  # Array containing the complete command line.
  #
  # source://clamby//lib/clamby/command.rb#7
  def command; end

  # Array containing the complete command line.
  #
  # source://clamby//lib/clamby/command.rb#7
  def command=(_arg0); end

  # Run the given commands via a system call.
  # The executable must be one of the permitted ClamAV executables.
  # The arguments will be combined with default arguments if needed.
  # The arguments are sorted alphabetically before being passed to the system.
  #
  # Examples:
  #   run('clamscan', file, '--verbose')
  #   run('clamscan', '-V')
  #
  # source://clamby//lib/clamby/command.rb#74
  def run(executable, *args); end

  private

  # source://clamby//lib/clamby/command.rb#84
  def default_args; end

  # source://clamby//lib/clamby/command.rb#101
  def executable_path(executable); end

  # This applies to the `system` call itself; does not end up in the command.
  #
  # source://clamby//lib/clamby/command.rb#93
  def system_options; end

  class << self
    # Show the ClamAV version. Also acts as a quick check if ClamAV functions.
    #
    # source://clamby//lib/clamby/command.rb#62
    def clamscan_version; end

    # @return [Boolean]
    #
    # source://clamby//lib/clamby/command.rb#106
    def file_exists?(path); end

    # Update the virus definitions.
    #
    # source://clamby//lib/clamby/command.rb#55
    def freshclam; end

    # Perform a ClamAV scan on the given path.
    #
    # source://clamby//lib/clamby/command.rb#21
    def scan(path); end

    # Returns the appropriate scan executable, based on clamd being used.
    #
    # source://clamby//lib/clamby/command.rb#10
    def scan_executable; end

    # $CHILD_STATUS maybe nil if the execution itself (not the client process)
    #
    # source://clamby//lib/clamby/command.rb#16
    def scan_status; end
  end
end

# source://clamby//lib/clamby/command.rb#4
Clamby::Command::EXECUTABLES = T.let(T.unsafe(nil), Array)

# source://clamby//lib/clamby.rb#7
Clamby::DEFAULT_CONFIG = T.let(T.unsafe(nil), Hash)

# source://clamby//lib/clamby/error.rb#2
class Clamby::Error < ::StandardError; end

# source://clamby//lib/clamby/error.rb#7
class Clamby::FileNotFound < ::Clamby::Error; end

# source://clamby//lib/clamby/version.rb#2
Clamby::VERSION = T.let(T.unsafe(nil), String)

# source://clamby//lib/clamby/error.rb#4
class Clamby::VirusDetected < ::Clamby::Error; end
