# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sentry-rails` gem.
# Please instead update this file by running `bin/tapioca gem sentry-rails`.


# source://sentry-rails//lib/sentry/rails/version.rb#3
module Sentry
  class << self
    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#225
    def add_attachment(**opts); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#319
    def add_breadcrumb(breadcrumb, **options); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#558
    def add_global_event_processor(&block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#113
    def apply_patches(config); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#85
    def background_worker; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#85
    def background_worker=(_arg0); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#93
    def backpressure_monitor; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#478
    def capture_check_in(slug, status, **options); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#462
    def capture_event(event); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#426
    def capture_exception(exception, **options, &block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#498
    def capture_log(message, **options); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#454
    def capture_message(message, **options, &block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#356
    def clone_hub_to_current_thread; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#258
    def close; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#165
    def configuration; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#372
    def configure_scope(&block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#602
    def continue_trace(env, **options); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#301
    def csp_report_uri; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#675
    def dependency_installed?(name); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#540
    def exception_captured?(exc); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#67
    def exception_locals_tp; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#575
    def get_baggage; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#340
    def get_current_client; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#329
    def get_current_hub; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#348
    def get_current_scope; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#309
    def get_main_hub; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#584
    def get_trace_propagation_headers; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#593
    def get_trace_propagation_meta; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#566
    def get_traceparent; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#236
    def init(&block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#289
    def initialized?; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#129
    def integrations; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#532
    def last_event_id; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#627
    def logger; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#645
    def metrics; end

    # source://railties/7.0.8.7/lib/rails/engine.rb#405
    def railtie_helpers_paths; end

    # source://railties/7.0.8.7/lib/rails/engine.rb#394
    def railtie_namespace; end

    # source://railties/7.0.8.7/lib/rails/engine.rb#409
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#137
    def register_integration(name, version); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#98
    def register_patch(key, patch = T.unsafe(nil), target = T.unsafe(nil), &block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#120
    def registered_patches; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#660
    def sdk_logger; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#665
    def sdk_meta; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#172
    def send_event(*args); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#89
    def session_flusher; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#218
    def set_context(*args); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#204
    def set_extras(*args); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#197
    def set_tags(*args); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#211
    def set_user(*args); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#506
    def start_transaction(**options); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#652
    def sys_command(command); end

    # source://railties/7.0.8.7/lib/rails/engine.rb#397
    def table_name_prefix; end

    # source://railties/7.0.8.7/lib/rails/engine.rb#401
    def use_relative_model_naming?; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#670
    def utc_now; end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#524
    def with_child_span(**attributes, &block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#443
    def with_exception_captured(**options, &block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#397
    def with_scope(&block); end

    # source://sentry-ruby/6.3.0/lib/sentry-ruby.rb#417
    def with_session_tracking(&block); end
  end
end

# source://sentry-rails//lib/sentry/rails/configuration.rb#12
class Sentry::Configuration
  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#483
  def initialize; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#32
  def app_dirs_pattern; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#32
  def app_dirs_pattern=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#284
  def auto_session_tracking; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#284
  def auto_session_tracking=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#49
  def background_worker_max_queue; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#49
  def background_worker_max_queue=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#42
  def background_worker_threads; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#42
  def background_worker_threads=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#60
  def backtrace_cleanup_callback; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#60
  def backtrace_cleanup_callback=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#69
  def before_breadcrumb; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#621
  def before_breadcrumb=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#82
  def before_send; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#597
  def before_send=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#107
  def before_send_check_in; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#609
  def before_send_check_in=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#116
  def before_send_log; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#116
  def before_send_log=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#356
  def before_send_metric; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#615
  def before_send_metric=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#95
  def before_send_transaction; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#603
  def before_send_transaction=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#127
  def breadcrumbs_logger; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#584
  def breadcrumbs_logger=(logger); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#135
  def context_lines; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#135
  def context_lines=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#253
  def cron; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#723
  def csp_report_uri; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#144
  def debug; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#144
  def debug=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#745
  def detect_release; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#148
  def dsn; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#572
  def dsn=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#290
  def enable_backpressure_handling; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#290
  def enable_backpressure_handling=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#271
  def enable_logs; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#271
  def enable_logs=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#343
  def enable_metrics; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#343
  def enable_metrics=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#152
  def enabled_environments; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#152
  def enabled_environments=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#701
  def enabled_in_current_env?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#335
  def enabled_patches; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#335
  def enabled_patches=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#139
  def environment; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#633
  def environment=(environment); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#758
  def error_messages; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#369
  def errors; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#688
  def exception_class_allowed?(exc); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#156
  def exclude_loggers; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#156
  def exclude_loggers=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#161
  def excluded_exceptions; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#161
  def excluded_exceptions=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#369
  def gem_specs; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#170
  def include_local_variables; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#170
  def include_local_variables=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#165
  def inspect_exception_causes_for_exclusion; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#165
  def inspect_exception_causes_for_exclusion=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#165
  def inspect_exception_causes_for_exclusion?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#311
  def instrumenter; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#637
  def instrumenter=(instrumenter); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#184
  def linecache; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#184
  def linecache=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#131
  def max_breadcrumbs; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#131
  def max_breadcrumbs=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#339
  def max_log_events; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#339
  def max_log_events=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#347
  def max_metric_events; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#347
  def max_metric_events=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#315
  def profiler_class; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#657
  def profiler_class=(profiler_class); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#330
  def profiles_sample_interval; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#330
  def profiles_sample_interval=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#321
  def profiles_sample_rate; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#653
  def profiles_sample_rate=(profiles_sample_rate); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#716
  def profiling_enabled?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#199
  def project_root; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#199
  def project_root=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#208
  def propagate_traces; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#208
  def propagate_traces=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#212
  def rack_env_whitelist; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#212
  def rack_env_whitelist=(_arg0); end

  # Returns the value of attribute rails.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#13
  def rails; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#217
  def release; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#578
  def release=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#678
  def sample_allowed?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#222
  def sample_rate; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#222
  def sample_rate=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#194
  def sdk_debug_transport_log_file; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#194
  def sdk_debug_transport_log_file=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#189
  def sdk_logger; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#189
  def sdk_logger=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#280
  def send_client_reports; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#280
  def send_client_reports=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#235
  def send_default_pii; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#235
  def send_default_pii=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#226
  def send_modules; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#226
  def send_modules=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#668
  def sending_allowed?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#672
  def sending_to_dsn_allowed?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#572
  def server=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#245
  def server_name; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#245
  def server_name=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#684
  def session_tracking?; end

  # source://sentry-sidekiq/6.3.0/lib/sentry/sidekiq/configuration.rb#5
  def sidekiq; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#239
  def skip_rake_integration; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#239
  def skip_rake_integration=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#178
  def spotlight; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#178
  def spotlight=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#733
  def stacktrace_builder; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#365
  def std_lib_logger_filter; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#627
  def std_lib_logger_filter=(value); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#204
  def strip_backtrace_load_path; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#204
  def strip_backtrace_load_path=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#275
  def structured_logging; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#307
  def trace_ignore_status_codes; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#641
  def trace_ignore_status_codes=(codes); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#295
  def trace_propagation_targets; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#295
  def trace_propagation_targets=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#257
  def traces_sample_rate; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#649
  def traces_sample_rate=(traces_sample_rate); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#267
  def traces_sampler; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#267
  def traces_sampler=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#710
  def tracing_enabled?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#249
  def transport; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#242
  def trusted_proxies; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#242
  def trusted_proxies=(_arg0); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#705
  def valid_sample_rate?(sample_rate); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#554
  def validate; end

  private

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#800
  def capture_in_environment?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#816
  def environment_from_env; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#771
  def excluded_exception?(incoming_exception); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#777
  def excluded_exception_classes; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#781
  def get_exception_class(x); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#765
  def init_dsn(dsn_string); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#785
  def matches_exception?(excluded_exception_class, incoming_exception); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#840
  def processor_count; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#834
  def run_callbacks(hook, event); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#830
  def running_on_heroku?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#793
  def safe_const_get(x); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#820
  def server_name_from_env; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#807
  def valid?; end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#845
  def valid_http_status_code?(code); end

  # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#849
  def valid_status_code_entry?(entry); end

  class << self
    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#423
    def add_post_initialization_callback(&block); end

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#431
    def after(event, &block); end

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#427
    def before(event, &block); end

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#436
    def callbacks; end

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#418
    def post_initialization_callbacks; end

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#447
    def validate(attribute, optional: T.unsafe(nil), type: T.unsafe(nil)); end

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#443
    def validations; end

    private

    # source://sentry-ruby/6.3.0/lib/sentry/configuration.rb#457
    def build_validation_proc(optional, type); end
  end
end

# source://sentry-rails//lib/sentry/rails/engine.rb#4
class Sentry::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.0.8.7/lib/active_support/callbacks.rb#68
    def __callbacks; end
  end
end

# source://sentry-rails//lib/sentry/rails/version.rb#4
module Sentry::Rails
  extend ::Sentry::Integrable
end

# source://sentry-rails//lib/sentry/rails/configuration.rb#66
Sentry::Rails::ACTIVE_SUPPORT_LOGGER_SUBSCRIPTION_ITEMS_DEFAULT = T.let(T.unsafe(nil), Hash)

# source://sentry-rails//lib/sentry/rails/backtrace_cleaner.rb#8
class Sentry::Rails::BacktraceCleaner < ::ActiveSupport::BacktraceCleaner
  # @return [BacktraceCleaner] a new instance of BacktraceCleaner
  #
  # source://sentry-rails//lib/sentry/rails/backtrace_cleaner.rb#12
  def initialize; end
end

# source://sentry-rails//lib/sentry/rails/backtrace_cleaner.rb#9
Sentry::Rails::BacktraceCleaner::APP_DIRS_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://sentry-rails//lib/sentry/rails/backtrace_cleaner.rb#10
Sentry::Rails::BacktraceCleaner::RENDER_TEMPLATE_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#5
class Sentry::Rails::CaptureExceptions < ::Sentry::Rack::CaptureExceptions
  # @return [CaptureExceptions] a new instance of CaptureExceptions
  #
  # source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#9
  def initialize(_); end

  private

  # source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#28
  def capture_exception(exception, env); end

  # source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#19
  def collect_exception(env); end

  # @return [Boolean]
  #
  # source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#54
  def show_exceptions?(exception, env); end

  # source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#38
  def start_transaction(env, scope); end

  # source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#24
  def transaction_op; end
end

# source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#6
Sentry::Rails::CaptureExceptions::RAILS_7_1 = T.let(T.unsafe(nil), FalseClass)

# source://sentry-rails//lib/sentry/rails/capture_exceptions.rb#7
Sentry::Rails::CaptureExceptions::SPAN_ORIGIN = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/configuration.rb#126
class Sentry::Rails::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#179
  def initialize; end

  # Set this option to true if you want Sentry to capture each retry failure
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#173
  def active_job_report_on_retry_error; end

  # Set this option to true if you want Sentry to capture each retry failure
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#173
  def active_job_report_on_retry_error=(_arg0); end

  # Hash of subscription items that will be shown in breadcrumbs active support logger.
  #
  # @return [Hash<String, Array<Symbol>>]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#170
  def active_support_logger_subscription_items; end

  # Hash of subscription items that will be shown in breadcrumbs active support logger.
  #
  # @return [Hash<String, Array<Symbol>>]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#170
  def active_support_logger_subscription_items=(_arg0); end

  # sentry-rails by default skips asset request' transactions by checking if the path matches
  #
  # ```rb
  # %r(\A/{0,2}#{::Rails.application.config.assets.prefix})
  # ```
  #
  # If you want to use a different pattern, you can configure the `assets_regexp` option like:
  #
  # ```rb
  # Sentry.init do |config|
  #   config.rails.assets_regexp = /my_regexp/
  # end
  # ```
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#166
  def assets_regexp; end

  # sentry-rails by default skips asset request' transactions by checking if the path matches
  #
  # ```rb
  # %r(\A/{0,2}#{::Rails.application.config.assets.prefix})
  # ```
  #
  # If you want to use a different pattern, you can configure the `assets_regexp` option like:
  #
  # ```rb
  # Sentry.init do |config|
  #   config.rails.assets_regexp = /my_regexp/
  # end
  # ```
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#166
  def assets_regexp=(_arg0); end

  # The threshold in milliseconds for the ActiveRecordSubscriber to capture the source location of the query
  # in the span data. Default is 100ms.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#151
  def db_query_source_threshold_ms; end

  # The threshold in milliseconds for the ActiveRecordSubscriber to capture the source location of the query
  # in the span data. Default is 100ms.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#151
  def db_query_source_threshold_ms=(_arg0); end

  # When the ActiveRecordSubscriber is enabled, capture the source location of the query in the span data.
  # This is enabled by default, but can be disabled by setting this to false.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#147
  def enable_db_query_source; end

  # When the ActiveRecordSubscriber is enabled, capture the source location of the query in the span data.
  # This is enabled by default, but can be disabled by setting this to false.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#147
  def enable_db_query_source=(_arg0); end

  # Rails 7.0 introduced a new error reporter feature, which the SDK once opted-in by default.
  # But after receiving multiple issue reports, the integration seemed to cause serious troubles to some users.
  # So the integration is now controlled by this configuration, which is disabled (false) by default.
  # More information can be found from: https://github.com/rails/rails/pull/43625#issuecomment-1072514175
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#131
  def register_error_subscriber; end

  # Rails 7.0 introduced a new error reporter feature, which the SDK once opted-in by default.
  # But after receiving multiple issue reports, the integration seemed to cause serious troubles to some users.
  # So the integration is now controlled by this configuration, which is disabled (false) by default.
  # More information can be found from: https://github.com/rails/rails/pull/43625#issuecomment-1072514175
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#131
  def register_error_subscriber=(_arg0); end

  # Rails catches exceptions in the ActionDispatch::ShowExceptions or
  # ActionDispatch::DebugExceptions middlewares, depending on the environment.
  # When `report_rescued_exceptions` is true (it is by default), Sentry will
  # report exceptions even when they are rescued by these middlewares.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#137
  def report_rescued_exceptions; end

  # Rails catches exceptions in the ActionDispatch::ShowExceptions or
  # ActionDispatch::DebugExceptions middlewares, depending on the environment.
  # When `report_rescued_exceptions` is true (it is by default), Sentry will
  # report exceptions even when they are rescued by these middlewares.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#137
  def report_rescued_exceptions=(_arg0); end

  # Some adapters, like sidekiq, already have their own sentry integration.
  # In those cases, we should skip ActiveJob's reporting to avoid duplicated reports.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#141
  def skippable_job_adapters; end

  # Some adapters, like sidekiq, already have their own sentry integration.
  # In those cases, we should skip ActiveJob's reporting to avoid duplicated reports.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#141
  def skippable_job_adapters=(_arg0); end

  # Configuration for structured logging feature
  #
  # @return [StructuredLoggingConfiguration]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#177
  def structured_logging; end

  # Returns the value of attribute tracing_subscribers.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#143
  def tracing_subscribers; end

  # Sets the attribute tracing_subscribers
  #
  # @param value the value to set the attribute tracing_subscribers to.
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#143
  def tracing_subscribers=(_arg0); end
end

# source://sentry-rails//lib/sentry/rails/configuration.rb#43
Sentry::Rails::IGNORE_DEFAULT = T.let(T.unsafe(nil), Array)

# Base class for Sentry log subscribers that extends ActiveSupport::LogSubscriber
# to provide structured logging capabilities for Rails components.
#
# This class follows Rails' LogSubscriber pattern and provides common functionality
# for capturing Rails instrumentation events and logging them through Sentry's
# structured logging system.
#
# @example Creating a custom log subscriber
#   class MySubscriber < Sentry::Rails::LogSubscriber
#   attach_to :my_component
#
#   def my_event(event)
#   log_structured_event(
#   message: "My event occurred",
#   level: :info,
#   attributes: {
#   duration_ms: event.duration,
#   custom_data: event.payload[:custom_data]
#   }
#   )
#   end
#   end
#
# source://sentry-rails//lib/sentry/rails/log_subscriber.rb#30
class Sentry::Rails::LogSubscriber < ::ActiveSupport::LogSubscriber
  include ::Sentry::LoggingHelper

  protected

  # Calculate duration in milliseconds from an event
  #
  # @param event [ActiveSupport::Notifications::Event] The event
  # @return [Float] Duration in milliseconds
  #
  # source://sentry-rails//lib/sentry/rails/log_subscriber.rb#71
  def duration_ms(event); end

  # Log a structured event using Sentry's structured logger
  #
  # @param message [String] The log message
  # @param level [Symbol] The log level (:trace, :debug, :info, :warn, :error, :fatal)
  # @param attributes [Hash] Additional structured attributes to include
  # @param origin [String] The origin of the log event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscriber.rb#60
  def log_structured_event(message:, level: T.unsafe(nil), attributes: T.unsafe(nil), origin: T.unsafe(nil)); end
end

# source://sentry-rails//lib/sentry/rails/log_subscriber.rb#33
Sentry::Rails::LogSubscriber::ORIGIN = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/log_subscribers/parameter_filter.rb#5
module Sentry::Rails::LogSubscribers; end

# LogSubscriber for ActionController events that captures HTTP request processing
# and logs them using Sentry's structured logging system.
#
# This subscriber captures process_action.action_controller events and formats them
# with relevant request information including controller, action, HTTP status,
# request parameters, and performance metrics.
#
# @example Usage
#   # Enable structured logging for ActionController
#   Sentry.init do |config|
#   config.enable_logs = true
#   config.rails.structured_logging = true
#   config.rails.structured_logging.subscribers = { action_controller: Sentry::Rails::LogSubscribers::ActionControllerSubscriber }
#   end
#
# source://sentry-rails//lib/sentry/rails/log_subscribers/action_controller_subscriber.rb#23
class Sentry::Rails::LogSubscribers::ActionControllerSubscriber < ::Sentry::Rails::LogSubscriber
  include ::Sentry::Rails::LogSubscribers::ParameterFilter

  # Handle process_action.action_controller events
  #
  # @param event [ActiveSupport::Notifications::Event] The controller action event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/action_controller_subscriber.rb#29
  def process_action(event); end

  private

  # source://sentry-rails//lib/sentry/rails/log_subscribers/action_controller_subscriber.rb#75
  def extract_status(payload); end

  # source://sentry-rails//lib/sentry/rails/log_subscribers/action_controller_subscriber.rb#90
  def level_for_request(payload); end
end

# LogSubscriber for ActionMailer events that captures email delivery
# and processing events using Sentry's structured logging system.
#
# This subscriber captures deliver.action_mailer and process.action_mailer events
# and formats them with relevant email information while respecting PII settings.
#
# @example Usage
#   # Enable structured logging for ActionMailer
#   Sentry.init do |config|
#   config.enable_logs = true
#   config.rails.structured_logging = true
#   config.rails.structured_logging.subscribers = { action_mailer: Sentry::Rails::LogSubscribers::ActionMailerSubscriber }
#   end
#
# source://sentry-rails//lib/sentry/rails/log_subscribers/action_mailer_subscriber.rb#22
class Sentry::Rails::LogSubscribers::ActionMailerSubscriber < ::Sentry::Rails::LogSubscriber
  include ::Sentry::Rails::LogSubscribers::ParameterFilter

  # Handle deliver.action_mailer events
  #
  # @param event [ActiveSupport::Notifications::Event] The email delivery event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/action_mailer_subscriber.rb#28
  def deliver(event); end

  # Handle process.action_mailer events
  #
  # @param event [ActiveSupport::Notifications::Event] The email processing event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/action_mailer_subscriber.rb#61
  def process(event); end
end

# LogSubscriber for ActiveJob events that captures background job execution
# and logs them using Sentry's structured logging system.
#
# This subscriber captures various ActiveJob events including job execution,
# enqueueing, retries, and failures with relevant job information.
#
# @example Usage
#   # Enable structured logging for ActiveJob
#   Sentry.init do |config|
#   config.enable_logs = true
#   config.rails.structured_logging = true
#   config.rails.structured_logging.subscribers = { active_job: Sentry::Rails::LogSubscribers::ActiveJobSubscriber }
#   end
#
# source://sentry-rails//lib/sentry/rails/log_subscribers/active_job_subscriber.rb#22
class Sentry::Rails::LogSubscribers::ActiveJobSubscriber < ::Sentry::Rails::LogSubscriber
  include ::Sentry::Rails::LogSubscribers::ParameterFilter

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_job_subscriber.rb#119
  def discard(event); end

  # Handle enqueue.active_job events
  #
  # @param event [ActiveSupport::Notifications::Event] The job enqueue event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_job_subscriber.rb#67
  def enqueue(event); end

  # Handle perform.active_job events
  #
  # @param event [ActiveSupport::Notifications::Event] The job performance event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_job_subscriber.rb#28
  def perform(event); end

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_job_subscriber.rb#95
  def retry_stopped(event); end

  private

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_job_subscriber.rb#146
  def filter_sensitive_arguments(arguments); end
end

# LogSubscriber for ActiveRecord events that captures database queries
# and logs them using Sentry's structured logging system.
#
# This subscriber captures sql.active_record events and formats them
# with relevant database information including SQL queries, duration,
# database configuration, and caching information.
#
# @example Usage
#   # Automatically attached when structured logging is enabled for :active_record
#   Sentry.init do |config|
#   config.enable_logs = true
#   config.rails.structured_logging = true
#   config.rails.structured_logging.subscribers = { active_record: Sentry::Rails::LogSubscribers::ActiveRecordSubscriber }
#   end
#
# source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#23
class Sentry::Rails::LogSubscribers::ActiveRecordSubscriber < ::Sentry::Rails::LogSubscriber
  include ::Sentry::Rails::LogSubscribers::ParameterFilter

  # Handle sql.active_record events
  #
  # @param event [ActiveSupport::Notifications::Event] The SQL event
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#32
  def sql(event); end

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#79
  def type_casted_binds(event); end

  private

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#93
  def build_log_message(statement_name); end

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#123
  def extract_db_config(payload); end

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#158
  def extract_db_config_fallback(connection); end

  # Rails 6.0 and earlier use spec API
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#132
  def extract_db_config_from_connection(connection); end

  # source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#101
  def maybe_add_db_config_attributes(attributes, payload); end
end

# source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#27
Sentry::Rails::LogSubscribers::ActiveRecordSubscriber::EMPTY_ARRAY = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/log_subscribers/active_record_subscriber.rb#26
Sentry::Rails::LogSubscribers::ActiveRecordSubscriber::EXCLUDED_NAMES = T.let(T.unsafe(nil), Array)

# Shared utility module for filtering sensitive parameters in log subscribers.
#
# This module provides consistent parameter filtering across all Sentry Rails
# log subscribers, leveraging Rails' built-in parameter filtering when available.
# It automatically detects the correct Rails parameter filtering API based on
# the Rails version and includes the appropriate implementation module.
#
# @example Usage in a log subscriber
#   class MySubscriber < Sentry::Rails::LogSubscriber
#   include Sentry::Rails::LogSubscribers::ParameterFilter
#
#   def my_event(event)
#   if Sentry.configuration.send_default_pii && event.payload[:params]
#   filtered_params = filter_sensitive_params(event.payload[:params])
#   attributes[:params] = filtered_params unless filtered_params.empty?
#   end
#   end
#   end
#
# source://sentry-rails//lib/sentry/rails/log_subscribers/parameter_filter.rb#24
module Sentry::Rails::LogSubscribers::ParameterFilter
  # Filter sensitive parameters from a hash, respecting Rails configuration.
  #
  # @param params [Hash] The parameters to filter
  # @return [Hash] Filtered parameters with sensitive data removed
  #
  # source://sentry-rails//lib/sentry/rails/log_subscribers/parameter_filter.rb#41
  def filter_sensitive_params(params); end

  class << self
    # source://sentry-rails//lib/sentry/rails/log_subscribers/parameter_filter.rb#28
    def backend; end
  end
end

# source://sentry-rails//lib/sentry/rails/log_subscribers/parameter_filter.rb#25
Sentry::Rails::LogSubscribers::ParameterFilter::EMPTY_HASH = T.let(T.unsafe(nil), Hash)

# Rails 8.1.1 introduced ActionController::TooManyRequests for rate limiting
# https://github.com/rails/rails/commit/73ecd0ced634e5177496677a2986ec3731c7e2ee
#
# source://sentry-rails//lib/sentry/rails/configuration.rb#62
Sentry::Rails::RAILS_8_1_1_IGNORE_DEFAULT = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/rescued_exception_interceptor.rb#5
class Sentry::Rails::RescuedExceptionInterceptor
  # @return [RescuedExceptionInterceptor] a new instance of RescuedExceptionInterceptor
  #
  # source://sentry-rails//lib/sentry/rails/rescued_exception_interceptor.rb#6
  def initialize(app); end

  # source://sentry-rails//lib/sentry/rails/rescued_exception_interceptor.rb#10
  def call(env); end

  # @return [Boolean]
  #
  # source://sentry-rails//lib/sentry/rails/rescued_exception_interceptor.rb#21
  def report_rescued_exceptions?; end
end

# source://sentry-rails//lib/sentry/rails/structured_logging.rb#11
module Sentry::Rails::StructuredLogging
  class << self
    # source://sentry-rails//lib/sentry/rails/structured_logging.rb#13
    def attach(config); end

    # source://sentry-rails//lib/sentry/rails/structured_logging.rb#22
    def detach(config); end
  end
end

# source://sentry-rails//lib/sentry/rails/configuration.rb#200
class Sentry::Rails::StructuredLoggingConfiguration
  # @return [StructuredLoggingConfiguration] a new instance of StructuredLoggingConfiguration
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#214
  def initialize; end

  # Enable or disable structured logging
  #
  # @return [Boolean]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#203
  def enabled; end

  # Enable or disable structured logging
  #
  # @return [Boolean]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#203
  def enabled=(_arg0); end

  # Returns true if structured logging should be enabled.
  #
  # @return [Boolean]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#221
  def enabled?; end

  # Hash of components to subscriber classes for structured logging
  #
  # @return [Hash<Symbol, Class>]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#207
  def subscribers; end

  # Hash of components to subscriber classes for structured logging
  #
  # @return [Hash<Symbol, Class>]
  #
  # source://sentry-rails//lib/sentry/rails/configuration.rb#207
  def subscribers=(_arg0); end
end

# source://sentry-rails//lib/sentry/rails/configuration.rb#209
Sentry::Rails::StructuredLoggingConfiguration::DEFAULT_SUBSCRIBERS = T.let(T.unsafe(nil), Hash)

# source://sentry-rails//lib/sentry/rails/tracing.rb#5
module Sentry::Rails::Tracing
  class << self
    # source://sentry-rails//lib/sentry/rails/tracing.rb#71
    def get_current_transaction; end

    # this is necessary because instrumentation events don't record absolute start/finish time
    # so we need to retrieve the correct time this way
    #
    # source://sentry-rails//lib/sentry/rails/tracing.rb#44
    def patch_active_support_notifications; end

    # source://sentry-rails//lib/sentry/rails/tracing.rb#8
    def register_subscribers(subscribers); end

    # source://sentry-rails//lib/sentry/rails/tracing.rb#61
    def remove_active_support_notifications_patch; end

    # source://sentry-rails//lib/sentry/rails/tracing.rb#20
    def subscribe_tracing_events; end

    # source://sentry-rails//lib/sentry/rails/tracing.rb#16
    def subscribed_tracing_events; end

    # source://sentry-rails//lib/sentry/rails/tracing.rb#12
    def subscribers; end

    # source://sentry-rails//lib/sentry/rails/tracing.rb#33
    def unsubscribe_tracing_events; end
  end
end

# source://sentry-rails//lib/sentry/rails/tracing/abstract_subscriber.rb#6
class Sentry::Rails::Tracing::AbstractSubscriber
  class << self
    # source://sentry-rails//lib/sentry/rails/tracing/abstract_subscriber.rb#41
    def record_on_current_span(duration:, **options); end

    # @raise [NotImplementedError]
    #
    # source://sentry-rails//lib/sentry/rails/tracing/abstract_subscriber.rb#8
    def subscribe!; end

    # source://sentry-rails//lib/sentry/rails/tracing/abstract_subscriber.rb#30
    def subscribe_to_event(event_names); end

    # source://sentry-rails//lib/sentry/rails/tracing/abstract_subscriber.rb#12
    def unsubscribe!; end
  end
end

# source://sentry-rails//lib/sentry/rails/tracing/action_view_subscriber.rb#8
class Sentry::Rails::Tracing::ActionViewSubscriber < ::Sentry::Rails::Tracing::AbstractSubscriber
  class << self
    # source://sentry-rails//lib/sentry/rails/tracing/action_view_subscriber.rb#13
    def subscribe!; end
  end
end

# source://sentry-rails//lib/sentry/rails/tracing/action_view_subscriber.rb#9
Sentry::Rails::Tracing::ActionViewSubscriber::EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/action_view_subscriber.rb#11
Sentry::Rails::Tracing::ActionViewSubscriber::SPAN_ORIGIN = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/tracing/action_view_subscriber.rb#10
Sentry::Rails::Tracing::ActionViewSubscriber::SPAN_PREFIX = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#9
class Sentry::Rails::Tracing::ActiveRecordSubscriber < ::Sentry::Rails::Tracing::AbstractSubscriber
  class << self
    # source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#26
    def subscribe!; end
  end
end

# source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#10
Sentry::Rails::Tracing::ActiveRecordSubscriber::EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#13
Sentry::Rails::Tracing::ActiveRecordSubscriber::EXCLUDED_EVENTS = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#12
Sentry::Rails::Tracing::ActiveRecordSubscriber::SPAN_ORIGIN = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#11
Sentry::Rails::Tracing::ActiveRecordSubscriber::SPAN_PREFIX = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/tracing/active_record_subscriber.rb#15
Sentry::Rails::Tracing::ActiveRecordSubscriber::SUPPORT_SOURCE_LOCATION = T.let(T.unsafe(nil), FalseClass)

# source://sentry-rails//lib/sentry/rails/tracing/active_storage_subscriber.rb#8
class Sentry::Rails::Tracing::ActiveStorageSubscriber < ::Sentry::Rails::Tracing::AbstractSubscriber
  class << self
    # source://sentry-rails//lib/sentry/rails/tracing/active_storage_subscriber.rb#26
    def subscribe!; end
  end
end

# source://sentry-rails//lib/sentry/rails/tracing/active_storage_subscriber.rb#9
Sentry::Rails::Tracing::ActiveStorageSubscriber::EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_storage_subscriber.rb#24
Sentry::Rails::Tracing::ActiveStorageSubscriber::SPAN_ORIGIN = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#8
class Sentry::Rails::Tracing::ActiveSupportSubscriber < ::Sentry::Rails::Tracing::AbstractSubscriber
  class << self
    # source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#46
    def operation_name(event_name); end

    # source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#31
    def subscribe!; end
  end
end

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#27
Sentry::Rails::Tracing::ActiveSupportSubscriber::EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#23
Sentry::Rails::Tracing::ActiveSupportSubscriber::FLUSH_EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#9
Sentry::Rails::Tracing::ActiveSupportSubscriber::READ_EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#19
Sentry::Rails::Tracing::ActiveSupportSubscriber::REMOVE_EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#29
Sentry::Rails::Tracing::ActiveSupportSubscriber::SPAN_ORIGIN = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/tracing/active_support_subscriber.rb#13
Sentry::Rails::Tracing::ActiveSupportSubscriber::WRITE_EVENT_NAMES = T.let(T.unsafe(nil), Array)

# source://sentry-rails//lib/sentry/rails/tracing.rb#6
Sentry::Rails::Tracing::START_TIMESTAMP_NAME = T.let(T.unsafe(nil), Symbol)

# it's just a container for the extended method
#
# source://sentry-rails//lib/sentry/rails/tracing.rb#76
module Sentry::Rails::Tracing::SentryNotificationExtension; end

# source://sentry-rails//lib/sentry/rails/version.rb#5
Sentry::Rails::VERSION = T.let(T.unsafe(nil), String)

# source://sentry-rails//lib/sentry/rails/railtie.rb#9
class Sentry::Railtie < ::Rails::Railtie
  # source://sentry-rails//lib/sentry/rails/railtie.rb#137
  def activate_structured_logging; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#128
  def activate_tracing; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#82
  def configure_cron_timezone; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#74
  def configure_project_root; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#78
  def configure_trusted_proxies; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#87
  def extend_controller_methods; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#103
  def inject_breadcrumbs_logger; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#120
  def override_streaming_reporter; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#99
  def patch_background_worker; end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#143
  def register_error_subscriber(app); end

  # source://sentry-rails//lib/sentry/rails/railtie.rb#112
  def setup_backtrace_cleanup_callback; end
end

class Sentry::SendEventJob < ::ActiveJob::Base
  def perform(event, hint = T.unsafe(nil)); end

  class << self
    # source://activejob/7.0.8.7/lib/active_job/logging.rb#12
    def log_arguments; end

    # source://activesupport/7.0.8.7/lib/active_support/rescuable.rb#13
    def rescue_handlers; end
  end
end
