# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tzinfo-data` gem.
# Please instead update this file by running `bin/tapioca gem tzinfo-data`.


# Top level module for TZInfo.
#
# source://tzinfo-data//lib/tzinfo/data.rb#2
module TZInfo; end

# Top level module for TZInfo::Data.
#
# source://tzinfo-data//lib/tzinfo/data.rb#4
module TZInfo::Data; end

# source://tzinfo-data//lib/tzinfo/data/indexes/timezones.rb#8
module TZInfo::Data::Indexes; end

# source://tzinfo-data//lib/tzinfo/data/indexes/countries.rb#9
module TZInfo::Data::Indexes::Countries
  include ::TZInfo::Format1::CountryIndexDefinition
  extend ::TZInfo::Format1::CountryIndexDefinition::ClassMethods
end

# source://tzinfo-data//lib/tzinfo/data/indexes/timezones.rb#9
module TZInfo::Data::Indexes::Timezones
  include ::TZInfo::Format1::TimezoneIndexDefinition
  extend ::TZInfo::Format1::TimezoneIndexDefinition::ClassMethods
end

# TZInfo::Data version number.
#
# source://tzinfo-data//lib/tzinfo/data/version.rb#4
TZInfo::Data::VERSION = T.let(T.unsafe(nil), String)

# TZInfo::Data version information.
#
# source://tzinfo-data//lib/tzinfo/data/version.rb#7
module TZInfo::Data::Version; end

# The format of the Ruby modules. The only format currently supported by
# TZInfo is version 1.
#
# source://tzinfo-data//lib/tzinfo/data/version.rb#10
TZInfo::Data::Version::FORMAT = T.let(T.unsafe(nil), Integer)

# TZInfo::Data version number.
#
# source://tzinfo-data//lib/tzinfo/data/version.rb#13
TZInfo::Data::Version::STRING = T.let(T.unsafe(nil), String)

# The version of the {IANA Time Zone Database}[https://www.iana.org/time-zones]
# used to generate this version of TZInfo::Data.
#
# source://tzinfo-data//lib/tzinfo/data/version.rb#17
TZInfo::Data::Version::TZDATA = T.let(T.unsafe(nil), String)
