import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { parse as parseYaml } from "yaml";
import { applyCodexHarness } from "./codex-harness.js";

const STUB_YML = `# harmonic-bridge agent config for "alice" — generated by 'harmonic-bridge add'.
# Edit wake_command and working_dir before relying on this agent.

harmonic_mcp_endpoint: https://app.harmonic.example/mcp
harmonic_token: file:///secrets/alice/harmonic_token
webhook_secret: file:///secrets/alice/webhook_secret

working_dir: /agents/alice

wake_command: |
  echo "wake_command not configured for $HARMONIC_BRIDGE_AGENT_NAME" >&2
  exit 1

events:
  - notifications.delivered
  - reminders.delivered
`;

function makeAgentDir(yml: string = STUB_YML): string {
  const dir = mkdtempSync(path.join(tmpdir(), "codex-harness-"));
  writeFileSync(path.join(dir, "harmonic-bridge.yml"), yml);
  return dir;
}

function readYml(dir: string): Record<string, unknown> {
  return parseYaml(readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8")) as Record<string, unknown>;
}

test("codex-harness: replaces the stub wake_command and writes system-prompt.md", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  const result = await applyCodexHarness({ agentDir: dir });
  assert.equal(result.updatedWakeCommand, true);
  assert.equal(result.wroteSystemPrompt, true);

  const yml = readYml(dir);
  const wake = yml["wake_command"] as string;

  assert.match(wake, /codex exec/);
  // working_dir is usually not a git repo, and the git check would refuse.
  assert.match(wake, /--skip-git-repo-check/);
  // Real work in the agent's own directory without danger-full-access.
  assert.match(wake, /--sandbox workspace-write/);
  // Unattended: nothing may stall waiting for an approval.
  assert.match(wake, /--ask-for-approval never/);

  // The MCP server arrives as three -c overrides parameterized on the agent
  // name; auth stays in the shared ~/.codex, so one login serves every agent.
  assert.match(wake, /-c "mcp_servers\.harmonic-\$HARMONIC_BRIDGE_AGENT_NAME\.url=\\"\$HARMONIC_BRIDGE_MCP_ENDPOINT\\""/);
  assert.match(wake, /-c "mcp_servers\.harmonic-\$HARMONIC_BRIDGE_AGENT_NAME\.bearer_token_env_var=\\"HARMONIC_BRIDGE_TOKEN\\""/);
  // required=true: a server that fails to start aborts the run instead of
  // silently proceeding without Harmonic tools (goose taught us that lesson).
  assert.match(wake, /-c "mcp_servers\.harmonic-\$HARMONIC_BRIDGE_AGENT_NAME\.required=true"/);

  // The prompt is the argument; the JSON payload arrives on stdin.
  assert.match(wake, /"\$\(cat "\$HARMONIC_BRIDGE_AGENT_DIR\/system-prompt\.md"\)"\s*$/);

  // The token is only ever named, never inlined.
  assert.doesNotMatch(wake, /Bearer /);

  assert.equal(yml["timeout_seconds"], 900);
  // Untouched fields survive.
  assert.equal(yml["harmonic_mcp_endpoint"], "https://app.harmonic.example/mcp");
  assert.deepEqual(yml["events"], ["notifications.delivered", "reminders.delivered"]);
});

test("codex-harness: the system prompt names Codex's tool surface", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyCodexHarness({ agentDir: dir });
  const prompt = readFileSync(path.join(dir, "system-prompt.md"), "utf8");

  assert.match(prompt, /shell/i);
  // MCP tools may appear namespaced by server, so the prompt must say so.
  assert.match(prompt, /harmonic-/);
  // Shared body still present.
  assert.match(prompt, /fetch_page on \/whoami/);
  assert.match(prompt, /execute_action/);
  assert.doesNotMatch(prompt, /Bash, Read, Write, Edit, Glob, Grep/, "Claude Code's tool names must not leak in");
  assert.doesNotMatch(prompt, /developer extension/, "goose's tool story must not leak in");
});

test("codex-harness: leaves a customized wake_command alone", async (t) => {
  const custom = STUB_YML.replace(/wake_command: \|\n(  .*\n)+/, "wake_command: |\n  my-custom-harness --run\n");
  const dir = makeAgentDir(custom);
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  const result = await applyCodexHarness({ agentDir: dir });
  assert.equal(result.updatedWakeCommand, false);

  const yml = readYml(dir);
  assert.match(yml["wake_command"] as string, /my-custom-harness --run/);
  assert.equal(yml["timeout_seconds"], undefined, "must not add timeout to a customized config");
});

test("codex-harness: does not overwrite an existing system-prompt.md", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  writeFileSync(path.join(dir, "system-prompt.md"), "MY CUSTOM PROMPT\n");

  const result = await applyCodexHarness({ agentDir: dir });
  assert.equal(result.wroteSystemPrompt, false);
  assert.equal(readFileSync(path.join(dir, "system-prompt.md"), "utf8"), "MY CUSTOM PROMPT\n");
});

test("codex-harness: is idempotent across two runs", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyCodexHarness({ agentDir: dir });
  const afterFirst = readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8");
  const second = await applyCodexHarness({ agentDir: dir });
  assert.equal(second.updatedWakeCommand, false, "already-applied harness must not rewrite");
  assert.equal(second.wroteSystemPrompt, false);
  assert.equal(readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8"), afterFirst);
});

test("codex-harness: preserves the generated config's comments", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyCodexHarness({ agentDir: dir });
  const raw = readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8");
  assert.match(raw, /# harmonic-bridge agent config for "alice"/);
});
