import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { parse as parseYaml } from "yaml";
import { applyGooseHarness } from "./goose-harness.js";

const STUB_YML = `# harmonic-bridge agent config for "alice" — generated by 'harmonic-bridge add'.
# Edit wake_command and working_dir before relying on this agent.

harmonic_mcp_endpoint: https://app.harmonic.example/mcp
harmonic_token: file:///secrets/alice/harmonic_token
webhook_secret: file:///secrets/alice/webhook_secret

working_dir: /agents/alice

wake_command: |
  echo "wake_command not configured for $HARMONIC_BRIDGE_AGENT_NAME" >&2
  exit 1

events:
  - notifications.delivered
  - reminders.delivered
`;

function makeAgentDir(yml: string = STUB_YML): string {
  const dir = mkdtempSync(path.join(tmpdir(), "goose-harness-"));
  writeFileSync(path.join(dir, "harmonic-bridge.yml"), yml);
  return dir;
}

function readYml(dir: string): Record<string, unknown> {
  return parseYaml(readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8")) as Record<string, unknown>;
}

test("goose-harness: replaces the stub wake_command and writes system-prompt.md", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  const result = await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  assert.equal(result.updatedWakeCommand, true);
  assert.equal(result.wroteSystemPrompt, true);

  const yml = readYml(dir);
  const wake = yml["wake_command"] as string;

  // XDG_CONFIG_HOME alone is honored on macOS and Linux (verified against
  // goose 1.44.0), so HOME stays untouched and the agent keeps its real
  // dotfiles — gitconfig, ssh — for shell work.
  assert.match(wake, /XDG_CONFIG_HOME="\$HARMONIC_BRIDGE_AGENT_DIR\/config"/);
  assert.doesNotMatch(wake, /\bHOME=/, "must not relocate HOME");

  assert.match(wake, /goose run/);
  // The payload is the instruction; the harness prompt is system context.
  assert.match(wake, /--system "\$\(cat "\$HARMONIC_BRIDGE_AGENT_DIR\/system-prompt\.md"\)"/);
  assert.match(wake, /-i -\s*$/);

  // Bounded by default: upstream's --max-turns default is 1000, which on a
  // hibernating host means a looping wake holds the machine awake and billing.
  assert.match(wake, /--no-session/);
  assert.match(wake, /--max-turns \d+/);
  assert.match(wake, /--max-tool-repetitions \d+/);
  assert.equal(yml["timeout_seconds"], 900);

  // Without this the agent has only the four Harmonic tools — which is a
  // defensible configuration, but not the one the system prompt describes.
  assert.match(wake, /--with-builtin developer/);

  // Untouched fields survive.
  assert.equal(yml["harmonic_mcp_endpoint"], "https://app.harmonic.example/mcp");
  assert.deepEqual(yml["events"], ["notifications.delivered", "reminders.delivered"]);
});

test("goose-harness: the system prompt names this harness's actual tool sources", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  const prompt = readFileSync(path.join(dir, "system-prompt.md"), "utf8");

  assert.match(prompt, /developer extension/);
  assert.match(prompt, /harmonic-alice/, "must name the agent's own extension, not a placeholder");
  // Shared body still present.
  assert.match(prompt, /fetch_page on \/whoami/);
  assert.match(prompt, /execute_action/);
  assert.doesNotMatch(prompt, /Bash, Read, Write, Edit, Glob, Grep/, "Claude Code's tool names must not leak in");
});

const STUB_YML_WITH_LLM = STUB_YML.replace(
  "webhook_secret: file:///secrets/alice/webhook_secret\n",
  "webhook_secret: file:///secrets/alice/webhook_secret\n" +
  "harmonic_llm_endpoint: https://llm.harmonic.example/v1\n" +
  "harmonic_llm_token: file:///secrets/alice/harmonic_llm_token\n" +
  "harmonic_llm_model: anthropic/claude-sonnet-4.6\n",
);

test("goose-harness: wires the LLM gateway into the wake env when the credential is present", async (t) => {
  const dir = makeAgentDir(STUB_YML_WITH_LLM);
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  const result = await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  assert.equal(result.updatedWakeCommand, true);

  const wake = readYml(dir)["wake_command"] as string;
  // Defer-to-operator semantics: an explicitly-set variable in the daemon's
  // environment always wins; the gateway credential is the default.
  assert.match(wake, /GOOSE_PROVIDER="\$\{GOOSE_PROVIDER:-openai\}"/);
  assert.match(wake, /GOOSE_MODEL="\$\{GOOSE_MODEL:-\$HARMONIC_BRIDGE_LLM_MODEL\}"/);
  assert.match(wake, /OPENAI_BASE_URL="\$\{OPENAI_BASE_URL:-\$HARMONIC_BRIDGE_LLM_ENDPOINT\}"/);
  assert.match(wake, /OPENAI_API_KEY="\$\{OPENAI_API_KEY:-\$HARMONIC_BRIDGE_LLM_TOKEN\}"/);
  // Still the same bounded goose invocation underneath.
  assert.match(wake, /goose run/);
  assert.match(wake, /XDG_CONFIG_HOME="\$HARMONIC_BRIDGE_AGENT_DIR\/config"/);
});

test("goose-harness: no gateway wiring when the agent has no LLM credential", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  const wake = readYml(dir)["wake_command"] as string;
  assert.doesNotMatch(wake, /GOOSE_PROVIDER/, "provider env stays fully operator-owned");
  assert.doesNotMatch(wake, /OPENAI_/);
});

test("goose-harness: leaves a customized wake_command alone", async (t) => {
  const custom = STUB_YML.replace(/wake_command: \|\n(  .*\n)+/, "wake_command: |\n  my-custom-harness --run\n");
  const dir = makeAgentDir(custom);
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  const result = await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  assert.equal(result.updatedWakeCommand, false);

  const yml = readYml(dir);
  assert.match(yml["wake_command"] as string, /my-custom-harness --run/);
  assert.equal(yml["timeout_seconds"], undefined, "must not add timeout to a customized config");
});

test("goose-harness: does not overwrite an existing system-prompt.md", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  writeFileSync(path.join(dir, "system-prompt.md"), "MY CUSTOM PROMPT\n");

  const result = await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  assert.equal(result.wroteSystemPrompt, false);
  assert.equal(readFileSync(path.join(dir, "system-prompt.md"), "utf8"), "MY CUSTOM PROMPT\n");
});

test("goose-harness: is idempotent across two runs", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  const afterFirst = readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8");
  const second = await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  assert.equal(second.updatedWakeCommand, false, "already-applied harness must not rewrite");
  assert.equal(second.wroteSystemPrompt, false);
  assert.equal(readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8"), afterFirst);
});

test("goose-harness: preserves the generated config's comments", async (t) => {
  const dir = makeAgentDir();
  t.after(() => rmSync(dir, { recursive: true, force: true }));

  await applyGooseHarness({ agentDir: dir, agentHandle: "alice" });
  const raw = readFileSync(path.join(dir, "harmonic-bridge.yml"), "utf8");
  assert.match(raw, /# harmonic-bridge agent config for "alice"/);
});
