# Core cloud primitives for a single-droplet Harmonic deployment.
# This is the "Tier 1 — provision only" module: it creates infrastructure and
# bootstraps Docker + the compose files via cloud-init. It does NOT run the app
# release — that stays with scripts/deploy.sh (see docs/INFRASTRUCTURE.md).

# Group everything under one DO project for tidy billing / teardown.
resource "digitalocean_project" "harmonic" {
  name        = "harmonic"
  description = "Harmonic production stack (managed by terraform)"
  purpose     = "Web Application"
  environment = "Production"
  resources = [
    digitalocean_droplet.web.urn,
    digitalocean_database_cluster.pg.urn,
    digitalocean_spaces_bucket.storage.urn,
  ]
}

# --- Compute ---------------------------------------------------------------

resource "digitalocean_droplet" "web" {
  name     = "harmonic-web"
  region   = var.region
  size     = var.droplet_size
  image    = var.droplet_image
  ssh_keys = var.ssh_key_fingerprints

  # cloud-init: install Docker, lay down /opt/harmonic, create the secrets
  # mount dir. Does NOT pull images or start the app — that's deploy.sh.
  user_data = templatefile("${path.module}/cloud-init.yaml.tftpl", {
    compose_repo = "https://github.com/ibis-coordination/Harmonic.git"
  })

  graceful_shutdown = true
}

# --- Managed Postgres ------------------------------------------------------
# Credentials are generated by DO and surface as (sensitive) outputs. They
# WILL be written to terraform state — this is why the backend must be
# encrypted. App secrets (Stripe, SES, etc.) are kept out of state via SOPS.

resource "digitalocean_database_cluster" "pg" {
  name       = "harmonic-pg"
  engine     = "pg"
  version    = var.pg_version
  size       = var.pg_size
  region     = var.region
  node_count = var.pg_node_count
}

resource "digitalocean_database_db" "harmonic" {
  cluster_id = digitalocean_database_cluster.pg.id
  name       = "harmonic_production"
}

resource "digitalocean_database_user" "harmonic" {
  cluster_id = digitalocean_database_cluster.pg.id
  name       = "harmonic"
}

# Only the droplet may reach Postgres.
resource "digitalocean_database_firewall" "pg" {
  cluster_id = digitalocean_database_cluster.pg.id
  rule {
    type  = "droplet"
    value = digitalocean_droplet.web.id
  }
}

# --- Object storage (ActiveStorage) ----------------------------------------

resource "digitalocean_spaces_bucket" "storage" {
  name   = var.spaces_bucket_name
  region = var.region
  acl    = "private"
}

# Scoped Spaces access key — limited to this one bucket, not account-wide.
# (Also lands in state; sensitive output below.)
resource "digitalocean_spaces_key" "storage" {
  name = "harmonic-activestorage"
  grant {
    bucket     = digitalocean_spaces_bucket.storage.name
    permission = "readwrite"
  }
}

# --- Network firewall ------------------------------------------------------
# Public surface is ONLY 80/443. SSH is restricted to ssh_allowed_cidrs.
# Note: cAdvisor (:8080) and any /metrics port must NEVER be public — they
# are reachable only inside the Docker network, never opened here.

resource "digitalocean_firewall" "web" {
  name        = "harmonic-web"
  droplet_ids = [digitalocean_droplet.web.id]

  inbound_rule {
    protocol         = "tcp"
    port_range       = "80"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }
  inbound_rule {
    protocol         = "tcp"
    port_range       = "443"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }
  inbound_rule {
    protocol         = "tcp"
    port_range       = "22"
    source_addresses = var.ssh_allowed_cidrs
  }

  # Allow all outbound (LLM APIs, SES, image pulls, Let's Encrypt).
  outbound_rule {
    protocol              = "tcp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
  outbound_rule {
    protocol              = "udp"
    port_range            = "1-65535"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
}
