# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AgentQueueProcessorJob`.
# Please instead update this file by running `bin/tapioca dsl AgentQueueProcessorJob`.


class AgentQueueProcessorJob
  class << self
    sig do
      params(
        subagent_id: ::String,
        tenant_id: ::String,
        block: T.nilable(T.proc.params(job: AgentQueueProcessorJob).void)
      ).returns(T.any(AgentQueueProcessorJob, FalseClass))
    end
    def perform_later(subagent_id:, tenant_id:, &block); end

    sig { params(subagent_id: ::String, tenant_id: ::String).void }
    def perform_now(subagent_id:, tenant_id:); end
  end
end
