# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReminderDeliveryJob`.
# Please instead update this file by running `bin/tapioca dsl ReminderDeliveryJob`.


class ReminderDeliveryJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: ReminderDeliveryJob).void)
      ).returns(T.any(ReminderDeliveryJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
