# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `VoteReceiptMailer`.
# Please instead update this file by running `bin/tapioca dsl VoteReceiptMailer`.


class VoteReceiptMailer
  class << self
    sig { params(user: T.untyped, decision: T.untyped, receipt: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def receipt_email(user:, decision:, receipt:); end
  end
end
