# typed: true

module Api::V1
  class InfoController < BaseController
    extend T::Sig

    def index
      render json: {
        name: 'Harmonic API',
        version: '1.0.0', # TODO: Use config variable to track version
        routes: api_routes_for_current_scope,
      }
    end

    private

    # Build the routes list dynamically from Rails' route table so it can't
    # drift away from reality. The scope (tenant vs collective vs workspace)
    # is inferred from the request path.
    sig { returns(T::Array[T::Hash[Symbol, T.untyped]]) }
    def api_routes_for_current_scope
      prefix = api_prefix_for_request
      return [] unless prefix

      Rails.application.routes.routes
        .filter_map do |r|
          path = r.path.spec.to_s.sub(/\(\.:format\)\z/, "")
          next unless path == prefix || path.start_with?("#{prefix}/")
          # Skip Rails' default `/new` and `/edit` paths: they're generated by
          # `resources` but the API controllers don't implement those actions.
          next if path.end_with?("/new") || path.end_with?("/edit")
          { path: path, verb: r.verb }
        end
        .group_by { |r| r[:path] }
        .map { |path, group| { path: path, methods: group.map { |g| g[:verb] }.uniq.sort } }
        .sort_by { |r| r[:path] }
    end

    sig { returns(T.nilable(String)) }
    def api_prefix_for_request
      case request.path
      when %r{\A/api/v1\z}
        "/api/v1"
      when %r{\A/collectives/[^/]+/api/v1\z}
        "/collectives/:collective_handle/api/v1"
      when %r{\A/workspace/[^/]+/api/v1\z}
        "/workspace/:collective_handle/api/v1"
      end
    end

    sig { returns(NilClass) }
    def current_resource_model
      nil
    end

    sig { returns(TrueClass) }
    def validate_scope
      true
    end

    sig { returns(NilClass) }
    def current_scope
      nil
    end

    sig { returns(NilClass) }
    def current_resource
      nil
    end
  end
end
