#!/bin/bash
#
# Git pre-commit hook for Harmonic
#
# This hook:
# 1. Checks if TODO comments were changed and reminds to update TODO_INDEX.md
#
# To install: ./scripts/setup-hooks.sh
# To bypass: git commit --no-verify
#

# Run TODO index check
if [[ -x "./scripts/check-todo-index.sh" ]]; then
    ./scripts/check-todo-index.sh
fi
